.github/workflows/post-merge.yml, .nycrc.yml, README.md, src/app/drivingLicence/controllers/validate.js, src/app/drivingLicence/controllers/validate.test.js, src/app/drivingLicence/fields.js, src/app/oauth2/middleware.test.js, src/assets/scss/application.scss
Updated references to point to driving Licence
=> LIME-159 - Updating references for driving licence FE skeleton

package.json, src/app/drivingLicence/controllers/details.test.js, src/app/drivingLicence/controllers/licence-Issuer.test.js, src/app/drivingLicence/controllers/licence-issuer.js, src/app/drivingLicence/controllers/validate.js, src/app/drivingLicence/controllers/validate.test.js, src/app/drivingLicence/fields.js, src/app/drivingLicence/steps.js, src/locales/en/default.yml, src/locales/en/fields.yml, src/views/drivingLicence/details.html
Updated hint/error text for details page that displays when a user is retrying, also added conditional logic for displaying DVA instead of DVLA in guidance text depending on their document selection in the licence-issuer screen
=> LIME-147 - Adding retry text/warnings to front end

src/locales/en/default.yml, src/locales/en/fields.yml
=> LIME-165 - Licence details page copy updates

src/views/errors/error.html
Changed the error title page to say "Sorry, there is a problem"
The title paged had an incorrect error message
=> LIME-188 - fixing error screen title

src/locales/en/default.yml, src/locales/en/fields.yml
text for hints and labels on the driving licence detail entry screen amended to match prototype
=> LIME-165 - field hint text/label updates on detail entry screen

src/locales/en/default.yml
`Prove Your Identity` hyperlink added.
- [LIME-142](https://govukverify.atlassian.net/browse/LIME-142)
=> LIME-142 - CRI Escape route

src/app/drivingLicence/controllers/validate.js, src/app/drivingLicence/fields.js, src/app/drivingLicence/fieldsHelper.js, src/app/drivingLicence/fieldsHelper.test.js, src/app/drivingLicence/steps.js, src/locales/en/fields.yml, src/views/drivingLicence/details.html
- Updated regex validation
- Added DVLA checks  to DOB and licence number
- [LIME-235](https://govukverify.atlassian.net/browse/LIME-235)
=> LIME-235 - Update validation to check DoB and Licence number match

src/app/drivingLicence/fields.js, src/app/drivingLicence/fieldsHelper.test.js, src/locales/en/default.yml, src/locales/en/fields.yml, src/views/drivingLicence/details.html
Updated hint text for retry screen, updated validation on licence number fields to provide correct error msg for special characters/spaces being included in fields input
Fixing issues found from E2E testing
=> LIME-171 - Updates to retry hint text and validation clean up

src/app.js, src/locales/cy/default.yml, src/locales/cy/fields.yml, src/locales/cy/pages.errors.yml, src/locales/cy/pages.yml
Added Welsh webpage translations
=> LIME-232 - Welsh translation

src/app/drivingLicence/fields.js, src/locales/cy/default.yml, src/locales/en/fields.yml
- [LIME-240](https://govukverify.atlassian.net/browse/LIME-240)
Points 1, 5-10 completed.
See ticket attachments for details.
=> LIME-240 - Fixes for error messages and validation triggers.

deploy/template.yaml, src/app/drivingLicence/fields.js
Added alerts and alarm config to DL frontend
To allow driving licence alerting
=> LIME-211: Added alerts for task count to DL frontend

deploy/template.yaml
Increased desired task count 
To align with other CRIs and match alerting
=> LIME-211: Increased desired task count

src/locales/en/pages.yml
What changed
Corrected the driving licence screen title 
Why did it change
To match the title with the h1 page
=> LIME-244 - corrected dl screen title

src/locales/cy/fields.yml
=> LIME-232 - Welsh translation validation msg fix

src/app/drivingLicence/fields.js, src/locales/en/fields.yml
- [LIME-240](https://govukverify.atlassian.net/browse/LIME-240)
=> LIME-240 - Fixes DoB validation message. Fixes name length validator.

src/app/drivingLicence/fields.js, src/locales/cy/fields.yml, src/locales/en/fields.yml
=> LIME-240 - Validation fixes

src/app/drivingLicence/fields.js, src/locales/en/fields.yml
=> Lime 240 - 

deploy/template.yaml
Updated import values
The values were different now we are using the V1 stacks
=> LIME-421: Updated template import names following use of v1 stacks

src/locales/cy/default.yml, src/locales/cy/pages.errors.yml, src/locales/en/default.yml, src/locales/en/pages.errors.yml
###What changed
This PR updates all content related to the One Login name change
=> LIME-404 - Content updates to reflect product name change

package.json
- Node modules updated (or added) to the correct version to patch known vulnerabilities.
- [LIME-472](https://govukverify.atlassian.net/browse/LIME-472)
[LIME-472]: https://govukverify.atlassian.net/browse/LIME-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-472 - Node vulnerabilities fixed.

src/app/drivingLicence/fields.js, src/app/drivingLicence/steps.js, src/locales/cy/default.yml, src/locales/cy/fields.yml, src/locales/en/default.yml, src/locales/en/fields.yml, src/views/drivingLicence/details.html
Added user consent checkbox for DVA
So user's are informed when capturing their consent to check their details
=> LIME-568 - Added user consent for DVA

src/app/drivingLicence/controllers/licence-Issuer.test.js, src/app/drivingLicence/controllers/licence-issuer.js, src/app/drivingLicence/fields.js, src/app/drivingLicence/steps.js, src/locales/cy/default.yml, src/locales/cy/fields.yml, src/locales/en/default.yml, src/locales/en/fields.yml, src/views/drivingLicence/details.html, src/views/drivingLicence/licence-issuer.html
Added user consent checkbox for DVLA
So user's are informed when capturing their consent to check their details
=> LIME-520 - Added user consent for DVLA

src/locales/cy/fields.yml, src/locales/en/fields.yml
Added DVA privacy notice link to consent
=> LIME-594 - Added DVA privacy notice link

src/app/drivingLicence/fields.js, src/app/drivingLicence/fieldsHelper.js
Tidied up and fixed validation for DVLA
=> LIME-662: Fixed DVLA specific validation and tidied up enhanced name validation

src/locales/cy/default.yml
=> LIME-681 - Cookie banner typo fix

.github/workflows/checks.yml, sonar-project.properties
Updated sonar properties to correct name
To allow pre merge checks to pass
=> LIME-583: Corrected property name for sonar

test/browser/features/DVA_Driving_Licence.feature, test/browser/features/DVLADrivingLicence.feature, test/browser/pages/DVADetailsEntryPage.js, test/browser/pages/DrivingLicencePage.js, test/browser/step_definitions/DrivingLicenceStepDefs.js, test/browser/util/TestDataCreator.js, test/mocks/mappings/dl-check-error.json, test/mocks/mappings/driving-licence-fail.json, test/mocks/mappings/driving-licence.json, test/mocks/mappings/drivingLicence-session-error.json, test/mocks/mappings/drivingLicence-slow.json
Take outstanding DL tests from the API repo to Frontend repo
https://govukverify.atlassian.net/browse/LIME-700
Proposed changes
Add the remaining front end test to Frontend repo
=> Lime 700 Take outstanding DL tests from the API repo

test/browser/features/DVLADrivingLicence.feature
Added additional acceptance tests
To allow testing of a bug of bug fix on issue dates
=> LIME-713: Added additional tests to cover ACs on LIME-713

sonar-project.properties
IPS-310 Sonarcloud Migration
IPS-310 Sonarcloud Migration
- [IPS-310](https://govukverify.atlassian.net/browse/IPS-310)
[IPS-310]: https://govukverify.atlassian.net/browse/IPS-310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-310 Sonarcloud Migration to govuk-one-login

deploy/template.yaml
Enable ECSAccess and APIGWAccess log group subscription filters
- [LIME-856](https://govukverify.atlassian.net/browse/LIME-856)
[LIME-856]: https://govukverify.atlassian.net/browse/LIME-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-856 Enable ECSAccess and APIGWAccess log group subscription filters

src/locales/cy/default.yml, src/locales/cy/pages.yml, src/locales/en/default.yml, src/locales/en/pages.yml
Ensuring support link opens in a new tab
Bug fix
- [LIME-834](https://govukverify.atlassian.net/browse/LIME-834)
[LIME-834]: https://govukverify.atlassian.net/browse/LIME-834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-834 Fixing bug for opening in a new tab

deploy/template.yaml, package.json, src/app.js, src/lib/config.js, test/browser/features/DVLADrivingLicence.feature, test/browser/pages/DrivingLicencePage.js, test/browser/step_definitions/DrivingLicenceStepDefs.js
Added config to set the log level to request and debug in the lower environments
To ensure log levels are always correctly set in the higher environments for hmpo-app and common express
=> LIME-868: Setting log level to request by default and debug for dev runs

.github/workflows/post-merge-to-build.yml, .github/workflows/post-merge-to-dev.yml, CODEOWNERS, Dockerfile, deploy/template.yaml
IPS-302 driving licence ECS dynatrace integration
IPS-302 driving licence ECS dynatrace integration
- [IPS-302](https://govukverify.atlassian.net/browse/IPS-302)
[IPS-302]: https://govukverify.atlassian.net/browse/IPS-302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-302 driving licence ECS dynatrace integration

test/browser/features/DVA_Driving_Licence.feature
Added tests to check character limits for DVA
=> DVA Character Limit tests

.github/workflows/post-merge-to-dev.yml
Enable deploy to dev from workflow.
To allow testing in the dev environment via dev env pipeline deployment.
- [LIME-727](https://govukverify.atlassian.net/browse/LIME-727)
[LIME-727]: https://govukverify.atlassian.net/browse/LIME-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-727 Allow deploy to dev from workflow

.github/dependabot.yml, .github/workflows/checks.yml, .github/workflows/codeql.yml, .github/workflows/i18n.yml, .github/workflows/post-merge-to-build.yml, .github/workflows/post-merge-to-dev.yml
Update workflows to:
* remove deprecations
* implement dev-platform actions
* prepare for canary deployments
The github workflows
* remove deprecations
* implement dev-platform actions
* prepare for canary deployments
- [IPS-447](https://govukverify.atlassian.net/browse/IPS-447)
- [IPS-480](https://govukverify.atlassian.net/browse/IPS-480)
- [IPS-503](https://govukverify.atlassian.net/browse/IPS-503)
- [IPS-532](https://govukverify.atlassian.net/browse/IPS-532)
[IPS-447]: https://govukverify.atlassian.net/browse/IPS-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-480]: https://govukverify.atlassian.net/browse/IPS-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-503]: …
=> Ips 447 fix workflow warnings

src/locales/cy/default.yml, src/locales/en/default.yml, test/browser/pages/DVADetailsEntryPage.js, test/browser/step_definitions/DrivingLicenceStepDefs.js
Adding target to support link in footer
=> LIME-1038 - Adding target to support link in footer

test/browser/features/English/DVA/DVA.feature, test/browser/features/Welsh/DVA/WelshDVA.feature, test/browser/pages/DVADetailsEntryPage.js, test/browser/step_definitions/DrivingLicenceStepDefs.js
Added test steps to support link test to read the updated text in support footer link.
- [LIME-XXXX](https://govukverify.atlassian.net/browse/LIME-XXX)
=> LIME-1038 Added test steps to support link test to read the updated text in support footer link.

test/browser/features/English/DVA/DVA.feature, test/browser/features/English/DVLA/DVLA.feature
Updated test scenarios for both DVLA/DVA
=> LIME-994 - Renaming test scenarios DL Front

.eslintignore, .nycrc.yml, package.json, sonar-project.properties, src/app-setup.js, src/app-setup.test.js, src/app.js, src/app/drivingLicence/featureSets.test.js, src/dynamo-session-config.js, src/router.integration.test.js, src/router.js, src/session-config.js, src/session-config.test.js, test/browser/features/English/DVA/DVA.feature, test/browser/features/English/DVLA/DVLA.feature, test/browser/support/setup.js
The app.js has been broken down into several classes in order to make it more easy to write unit tests for.
We needed to improve test coverage in our front end in order to meet standards required by HMRC.
- [LIME-758](https://govukverify.atlassian.net/browse/LIME-758)
[LIME-758]: https://govukverify.atlassian.net/browse/LIME-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-758 improving test coverage in front-end

deploy/template.yaml
Enabling welsh toggle in production and integration for driving licence
=> LIME-1176: Enabling welsh toggle in production and integration

deploy/template.yaml
Toggled on GA4 in integration and production
To enable GA4 in production
=> LIME-1173: Enabling GA4 in production and integration

.github/workflows/checks.yml, .pre-commit-config.yaml, .secrets.baseline
- Added pre-commit GHA workflow step
- Updated pre-commit-config with `detect-secrets`
- Added secrets.baseline
- As per ticket requirements
- [IPS-484](https://govukverify.atlassian.net/browse/IPS-484)
[IPS-484]: https://govukverify.atlassian.net/browse/IPS-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-487: Add pre-commit GHA workflow and update pre-commit-config

.github/workflows/post-merge-to-build.yml, .github/workflows/post-merge-to-dev.yml
- [LIME-XXXX](https://govukverify.atlassian.net/browse/LIME-XXXX)
=> IPS-810 - Updated upload actions ECR versions

src/locales/cy/fields.yml, src/locales/cy/pages.yml
Add Welsh translation for Check your Details screen
Welsh translation added to locales
- [LIME-1313](https://govukverify.atlassian.net/browse/LIME-1313)
[LIME-1313]: https://govukverify.atlassian.net/browse/LIME-1313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1313 Welsh translation for CYD

src/views/drivingLicence/check-your-details.html
Added Date Formatting Filter to display dates in desired format
=> LIME-1493 - Updating date formats

deploy/template.yaml, package.json, src/app-setup.js
Added Frontend Vital Signs for logging values insightful for capacity
=> LIME-1343 - Added FE Vital Signs logging

.secrets.baseline, Dockerfile, deploy/template.yaml, src/app.js, yarn.lock
Healthcheck configured and Dockerfile command amended to create unique DYNATRACE_HOST_ID value for different containers. 
The healthcheck ensures fast failure if containers are taking to long to respond. Having unique DYNATRACE_HOST_ID values allows for monitoring of different containers. 
- [LIME-1345](https://govukverify.atlassian.net/browse/LIME-1345)
- [LIME-1351](https://govukverify.atlassian.net/browse/LIME-1351)
Same amendments made to Fraud and Passport.
- Successful user journey carried out locally 
- FE unit tests and feature tests passing:
- BE UI Feature tests passing (@stub tests in dev environment):
- Confirmed DL /healthcheck route working:
- Confirmed DL healthcheck task works:
[LIME-1345]: https://govukverify.atlassian.net/browse/LIME-1345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
=> LIME-1345 healthcheck configured

package.json
Downgraded Common Express due to issues discovered with the cookie banner
=> LIME-1350 - Downgrading Common-Express v8

deploy/template.yaml
Set Feature toggle for authSource enabled to true in prod/integration for go-live
=> LIME-1389 - Setting AuthSourceEnabled to True

src/app/drivingLicence/controllers/root.js
Added logging for when authSource is set to true
=> LIME-1389 - Additional Logging for AuthSourceRoute

src/app/drivingLicence/controllers/root.js
Changed info logs to warn for debugging go-live issues with auth Source in prod
=> LIME-1389 - Changing info logs to warn

deploy/template.yaml
=> LIME-1389 - Toggling AuthSourceEnabled to True

package.json, src/app/drivingLicence/overloadProtection.js, src/app/drivingLicence/overloadProtection.test.js, src/router.js
Added Front End Vital Signs metrics
=> LIME-1343 - Implementing Overload Protection/Adding Vital signs logging

deploy/template.yaml, package.json, src/app.js
- [LIME-XXXX](https://govukverify.atlassian.net/browse/LIME-XXXX)
=> LIME-1512 Common Express updated with cookie banner fix

deploy/template.yaml, yarn.lock
Increase task size so Node has a second CPU per container
To improve event-loop latency/performance
- [LIME-1552](https://govukverify.atlassian.net/browse/LIME-1552)
- [DCP-4451](https://govukverify.atlassian.net/browse/DCP-4451)
[LIME-1552]: https://govukverify.atlassian.net/browse/LIME-1552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DCP-4451]: https://govukverify.atlassian.net/browse/DCP-4451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1552 - Increase task size so Node has a second CPU per container

src/views/drivingLicence/check-your-details.html, test/browser/features/English/DVA/DVAAuthSource.feature, test/browser/features/English/DVLA/DVLAAuthSource.feature, test/browser/pages/CheckYourDetailsPage.js, test/browser/step_definitions/CheckYourDetailsStepDefs.js
Updated Date formatting on Check Your Details page to appear with spaces instead of hyphens.
e.g 12-12-2012 turns to 12 12 2012
=> LIME-1493 - Updating Date formatting

Dockerfile
=> LIME-1351 - Fixing host name

deploy/template.yaml
Correct typo in feature flag
To unblock deployment in Integration
- [LIME-1635](https://govukverify.atlassian.net/browse/LIME-1635)
[LIME-1635]: https://govukverify.atlassian.net/browse/LIME-1635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1635 Correct FeatureFlag name in integration
