govuk-one-login/ipv-cri-dl-front

deploy/template.yaml

Removed old references to fraud
To fix a broken pipeline deployment

LIME-160: Removed leftover references to Fraud

---

src/app/drivingLicence/fields.js

Upped postcode length to 8 characters
To allow users with spaces in there postcodes

LIME-165: Added additional character to max length check to facilitate spaces in post codes

---

src/locales/en/default.yml
src/locales/en/pages.yml
src/views/drivingLicence/licence-issuer.html

Updated licence-issuer screen to include additional guidance on the differentiation between DVA/DVLA for driving licence details entry
To reduce confusion surrounding driving licence issuers

LIME-401 - Licence-Issuer screen updated with details dropdown

---

src/views/drivingLicence/licence-issuer.html

Moved details dropdown below submit button
To Make page in line with content designers specification

LIME-401 - Moving Details dropdown to below submit

---

package.json
src/app/drivingLicence/fields.js
src/locales/cy/fields.yml
src/locales/en/fields.yml

- Welsh translation added for radio button divider "or"
~See: https://github.com/HMPO/hmpo-components/pull/138~
See: https://github.com/HMPO/hmpo-components/pull/139
- Translation was not supported prior to this ticket.
- [LIME-254](https://govukverify.atlassian.net/browse/LIME-254)
[LIME-254]: https://govukverify.atlassian.net/browse/LIME-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-254 - "or" divider on licence issuer screen displaying as English (Welsh Translation).

---

src/locales/cy/fields.yml

Corrected neu spelling in DL frontend
To reflect the correct Welsh translation

LIME-655 - Corrected neu spelling in DL frontend

---

src/views/drivingLicence/details.html

Previous fix to prevent accidental form submission via enter button presses during form input is overly board - preventing all enter button based form submission
When using keyboard navigation it should be valid to press enter when the submit button is focused
- [LIME-661](https://govukverify.atlassian.net/browse/LIME-661)
[LIME-661]: https://govukverify.atlassian.net/browse/LIME-661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-661 Allow enter button form submission when submit button is focused in keyboard navigation

---

package.json
yarn.lock

Update common-express to v1.0.0
Update dependancies to versions used by common-express v1.0.0
- i18next-http-middleware@3.3.0
- i18next@22.4.14
common-express v1.0.0 contains a fix for missing localisation text when accepting/rejecting the cookie banner
- [LIME-665](https://govukverify.atlassian.net/browse/LIME-665)
- [LIME-633](https://govukverify.atlassian.net/browse/LIME-633)
- [common-express v1.0.0](https://github.com/alphagov/di-ipv-cri-common-express/releases/tag/v1.0.0)
[LIME-665]: https://govukverify.atlassian.net/browse/LIME-665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-633]: https://govukverify.atlassian.net/browse/LIME-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-665 Update common-express to v1.0.0. to bring in cookie banner localisation fix

---

src/app/drivingLicence/fields.js

- During compilation of the JS, some functions are cached for later use. One of these functions attempts to get today's date. Due to this, `TODAY` will always been  read as the date  of compilation and not the user's date.
- This change removes the function call, relaying that responsibility to the `before` / `after` functions where checks are done. These functions are unaffected by the caching.
- [LIME-713](https://govukverify.atlassian.net/jira/software/c/projects/LIME/issues/LIME-713)
- Due to timezone conversion to UTC, `TODAY` is still one day out during BST. This should be taken into consideration during further testing.
[LIME-713]: https://govukverify.atlassian.net/browse/LIME-713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-713 - Hotfix to address JS caching the compilation date  as `TODAY`.

---

test/browser/features/DVA_Driving_Licence.feature
test/browser/features/WelshDrivingLicence.feature
test/browser/features/Welsh_DVA_Driving_Licence.feature
test/browser/pages/DVADetailsEntryPage.js
test/browser/pages/DrivingLicencePage.js
test/browser/pages/UniversalSteps.js
test/browser/pages/index.js
test/browser/step_definitions/DrivingLicenceStepDefs.js
test/browser/step_definitions/UniversalStepDefs.js

Added tests to cover welsh translation
So that we can remove tests from the api repo and improve pipeline speed

LIME-722: Added frontend tests to cover welsh translation

---

src/locales/cy/fields.yml
src/locales/en/fields.yml

Updated the DVA link for privacy notice instead of routing the user to a PDF which had been removed
To fix the broken link
- [LIME-847](https://govukverify.atlassian.net/browse/LIME-847)
[LIME-847]: https://govukverify.atlassian.net/browse/LIME-847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-847 updating link for DVA privacy notice

---

src/app/drivingLicence/fields.js
src/app/drivingLicence/fieldsHelper.js
src/app/drivingLicence/fieldsHelper.test.js
test/browser/features/DVLADrivingLicence.feature
test/browser/pages/DrivingLicencePage.js

Adding logic to fieldHelper to set new limits for name fields and adding validation checks for combining first and middle names
- [LIME-816](https://govukverify.atlassian.net/browse/LIME-816)
[LIME-816]: https://govukverify.atlassian.net/browse/LIME-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-816 DVLA DL CRI names character limit bug

---

src/app/drivingLicence/fieldsHelper.js

Bug in fieldshelper.js meant that dob was undefined, causing the FE to crash, fix is to wrap the dob in a nullcheck

LIME-849 - Fixing DOB/Licence number validation for DVLA

---

deploy/template.yaml

Align task scaling with latest CoreFront/AddressFront configurations.
Removed all maps and swapped to using the global EnvironmentConfiguration map.
Scaling did not operate correctly during the previous DL performance test.
CoreFront/AddressFront have ran the most recent tests (similar values), using these values, to establish a base line of the same configuration in the next DL performance test.
EnvironmentConfiguration to avoid creating maps for each parameter and allow direct comparison with core-front configuration
- [LIME-727](https://govukverify.atlassian.net/browse/LIME-727)
[LIME-727]: https://govukverify.atlassian.net/browse/LIME-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-727 Align task scaling with CoreFront/AddressFront configuration

---

deploy/template.yaml

Set desiredTaskCount to 2 for all envs
To avoid triggering DLOnlyOneTaskCountAlarm in non-prod
- [LIME-727](https://govukverify.atlassian.net/browse/LIME-727)
[LIME-727]: https://govukverify.atlassian.net/browse/LIME-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-727 Set desiredTaskCount to 2 for all envs to avoid triggering DLOnlyOneTaskCountAlarm in non-prod

---

src/app/drivingLicence/controllers/details.js
src/app/drivingLicence/controllers/details.test.js
test/browser/features/English/DVA/DVA.feature
test/browser/features/English/DVLA/DVLA.feature

The functionality for dates has been changed so the webform will only accept a four digit year value. If someone tries to input two digits, they will be informed they should enter the value as it appears on their driving licence.
This was changed due to a bug where users were allowed to enter a two digit expiry date but the logic was assuming it was '19' instead of '20' for the century.
- [LIME-850](https://govukverify.atlassian.net/browse/LIME-850)
[LIME-850]: https://govukverify.atlassian.net/browse/LIME-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-850 DoB, issue date and expiry to only accept 4 digits

---

src/app/drivingLicence/fields.js
src/locales/cy/default.yml
src/locales/cy/fields.yml
src/locales/cy/pages.yml
src/locales/en/default.yml
src/locales/en/fields.yml
src/locales/en/pages.yml

Removing any logic referring to prove another way web pages
To allow for a direct referral back to Core.
- [LIME-714](https://govukverify.atlassian.net/browse/LIME-714)
[LIME-714]: https://govukverify.atlassian.net/browse/LIME-714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-714 removing prove another way logic

---

src/views/drivingLicence/details.html
src/views/drivingLicence/licence-issuer.html
src/views/errors/error.html
src/views/errors/page-not-found.html
src/views/errors/session-ended.html

- Updated all the  taxonomy level 2 values for the PageViewTracker to "driving licence"
- Refactored the structure of the licence-issuer Nunjucks file to address an issue with the formResponse tracker. The tracker was unable to correctly push the value for the section parameter. As a solution, I added an h1 element with a rel attribute, allowing the formResponse tracker to recognise and retrieve it as the section value.
- Upgrade to latest version of the package- version 0.0.10
Fix Bugs / Improve GA4 Implementation 
**How our form trackers get the section value for a form input**
- [DFC-464](https://govukverify.atlassian.net/browse/DFC-464)
- [DFC-453](https://govukverify.atlassian.net/browse/DFC-453)
[DFC-464]: https://govukverify.atlassian.net/browse/DFC-464?atlOrigin=eyJpIjoiNWRkNTljNzY …

DFC 464 |  GA4 Implementation Update

---

deploy/template.yaml
package.json
src/app/drivingLicence/controllers/validate.js
yarn.lock

A new version of common-express has been introduced, so we can pass through headers for cloudfront correctly.
- [LIME-1127](https://govukverify.atlassian.net/browse/LIME-1127)
[LIME-1127]: https://govukverify.atlassian.net/browse/LIME-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1127 changes to headers for cloudfront

---

deploy/template.yaml

IPS-741 Lime CloudFront Link
Enabled CloudFront Distribution WAF Link in all environments inc Prod
- CloudFront WAF Link is in count mode in prod right now, this enables the actual WAF link in blocking mode in all envs.
modified:   deploy/template.yaml
- [IPS-741](https://govukverify.atlassian.net/browse/IPS-741)
[IPS-741]: https://govukverify.atlassian.net/browse/IPS-741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-741 Lime CloudFront Link

---

deploy/template.yaml

- Added resources to enable canary deployments, as detailed by devplatform in https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3821732161/ECS+-+Canary+Deployments+Migration+Guidance
- Resources include:
-  Deployment controller 
-  Second target group for green deployment
-  Canary deployment nested stack
-  5xx alarm for target group
- First of 2 PRs to enable canary deployments
- [IPS-537](https://govukverify.atlassian.net/browse/IPS-537)
- [IPS-555](https://govukverify.atlassian.net/browse/IPS-555)
- [LIME-XXXX](https://govukverify.atlassian.net/browse/LIME-XXXX)
[IPS-537]: https://govukverify.atlassian.net/browse/IPS-537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-555]: …

IPS-555: Add resources for canary deployment (stage 1)

---

deploy/template.yaml

To be merged after https://github.com/govuk-one-login/ipv-cri-check-hmrc-front/pull/248
- Updated TaskDefintion
- Removed NetworkConfiguration and LoadBalancers property from your ECS Service resource. 
- Second of 2 PRs to enable canary deployments
- To enable canary deployments
- Other config commented out to avoid errors, see step 7: https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3821732161/ECS+-+Canary+Deployments+Migration+Guidance
- [IPS-532](https://govukverify.atlassian.net/browse/IPS-532)
- [IPS-555](https://govukverify.atlassian.net/browse/IPS-555)
[IPS-532]: https://govukverify.atlassian.net/browse/IPS-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-555]: https://govukverify.atlassian.net/browse/IPS-555?atlOrigin=ey …

IPS-555: Enable canary deployment (stage 2)

---

src/views/drivingLicence/details.html
src/views/drivingLicence/licence-issuer.html
src/views/errors/error.html
src/views/errors/page-not-found.html
src/views/errors/session-ended.html

Taxonomy Level 1 value for all pages updated from "cri" to "web cri" as requested by the Data & Analytics team
As part of the CI changes following GA4 go live
(DFC-640)[https://govukverify.atlassian.net/browse/DFC-640]

DFC-640 | GA4| Update taxonomy level1 for pageViewTracker

---

package.json
yarn.lock

Updated nyc dependency to most up to date version (17.0.0). Deleted yarn.lock. Ran yarn install to generate new yarn.lock
Vulnerabilities detected in Lime frontend (FE) repos relating to babel/traverse. Babel is a sub dependency of nyc and older versions were found in existing nyc version.
- [LIME-1224](https://govukverify.atlassian.net/browse/LIME-1224)
[LIME-1224]: https://govukverify.atlassian.net/browse/LIME-1224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1224 Address babel/traverse vulnerabilities in nyc dependency

---

package.json
src/app.test.js
src/dynamo-session-config.js
yarn.lock

Upgrade aws-sdk V2 to V3 as AWS SDK for JavaScript v2 entered maintenance mode on September 8, 2024.
Upgraded aws-sdk in package.json to V3.
Dynamo session config and app.test were updated to reflect the V3 format
- [LIME-1266](https://govukverify.atlassian.net/browse/LIME-1266)
[LIME-1192]: https://govukverify.atlassian.net/browse/LIME-1192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1266]: https://govukverify.atlassian.net/browse/LIME-1266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LIME-1266] Upgrade to aws-sdk V3

---

deploy/template.yaml

Set ActionsEnabled to true for newly deployed alarms from this [PR](https://github.com/govuk-one-login/ipv-cri-dl-front/pull/269)
Change required for the alarms to work and notify to slack if they are triggered. 
- [IPS-655](https://govukverify.atlassian.net/browse/IPS-655)
[IPS-655]: https://govukverify.atlassian.net/browse/IPS-655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-655 sets actionsenabled to true for newly deployed alarms

---

.github/workflows/post-merge-to-build.yml
.github/workflows/post-merge-to-dev.yml

Updated workflows to sign the container image
Container signing is enforced by the canary lambda pipeline version so this change needs to be in place beforehand
- [IPS-1123](https://govukverify.atlassian.net/browse/IPS-1123)
The pipelines need to be updated to include the signing key in conjunction with this change
[IPS-1123]: https://govukverify.atlassian.net/browse/IPS-1123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1123 Use dev-platform action to sign images

---

package.json
yarn.lock

Update ExpressJS to 4.21.0
Updating a dep to the most current version.
To test canaries in the front pipeline.
- [LIME-XXXX](https://govukverify.atlassian.net/browse/LIME-XXXX)

BAU-Canary-Test Update ExpressJS to 4.21.0

---

src/locales/cy/default.yml
src/locales/en/default.yml
src/views/errors/error.html
src/views/errors/page-not-found.html
src/views/errors/session-ended.html

Welsh lang default yml updated to include welsh lang version of copyright text. views/errors/ html files also updated to allow update in default yml to come through on error pages. 
Previously the Welsh language version of pages included footer text relating to copyright in English. 
- [LIME-873](https://govukverify.atlassian.net/browse/LIME-873)
I have found that no content text is provided for the sessionEnded error page in the pages.yml file in any of the fraud, passport or DL CRIs so the browser literally displays the text ‘_sessionEnded.content_’.  See jira ticket for screenshot. This may require another ticket being generated to provide content text that can be shown on the sessionEnded error pages? 
[LIME-873]: https://govukverify.atlassian.net/browse/LIME-873?atlOrigin=eyJpIjoiNWRk …

Welsh lang copyright wording added

---

test/browser/features/Welsh/DVA/WelshDVA.feature
test/browser/features/Welsh/DVLA/WelshDVLA.feature
test/browser/pages/DrivingLicencePage.js
test/browser/step_definitions/DrivingLicenceStepDefs.js

Added new Tests to check the Footer Links when on the DVLA and DVA start pages show correctly in Welsh Language
Following changes to [LIME-873](https://govukverify.atlassian.net/browse/LIME-873) 
- [LIME-1299](https://govukverify.atlassian.net/browse/LIME-1299)
All FE Tests passed locally in Dev:
[LIME-1299]: https://govukverify.atlassian.net/browse/LIME-1299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-873]: https://govukverify.atlassian.net/browse/LIME-873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1299]: https://govukverify.atlassian.net/browse/LIME-1299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1299: Added Welsh Lang Tests for DVLA and DVA Footer Links

---

.github/workflows/checks.yml
.github/workflows/post-merge-to-build.yml
.github/workflows/post-merge-to-dev.yml
.pre-commit-config.yaml
deploy/template.yaml

- Add SAM validate on pre-merge checks and lint on the pre and post merge checks
- Ran `pre-commit autoupdate`
The following change was required to pass the new linting steps:
1. Create condition for `HealthCheckGracePeriodSeconds` (this Property is only used if canaries are disabled ie if the service is using a load balancer and not managed by CodeDeploy). This was to fix `E3056 | ECS service using HealthCheckGracePeriodSeconds must also have LoadBalancers specified` [E3056](https://github.com/aws-cloudformation/cfn-lint/blob/main/src/cfnlint/rules/resources/ecs/ServiceHealthCheckGracePeriodSeconds.py) See the docs at:
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_parameters.html
- https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3821732161/ECS+- …

IPS-1132: Add linting

---

.secrets.baseline
deploy/template.yaml

Align DL F.E scaling with HMRC KBV F.E with MinCapacity at 4 
Preparation for a new performance test to establish the current performance baseline.
MinCapacity 4 aimed at handling large initial burst traffic from 0% load
- [LIME-1208](https://govukverify.atlassian.net/browse/LIME-1208)
[LIME-1208]: https://govukverify.atlassian.net/browse/LIME-1208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1208 - Align DL F.E scaling with HMRC KBV F.E

---

.secrets.baseline
deploy/template.yaml
src/app/drivingLicence/controllers/root.js
src/app/drivingLicence/controllers/root.test.js
src/app/drivingLicence/controllers/validate.js
src/lib/config.js

- Updated Root.js Controller to call new personInfo Endpoint and map returned values into sessionModel
- made mapping of values to sessionModel conditional for compatibility with existing web route
- Updated Config to include new personInfo endpoint path
- Added tests for root controller

LIME-1273 - Adding new call to personInfo endpoint

---

src/locales/cy/pages.yml

Welsh translation added to welsh yaml for consent screen 
To provide welsh translation for consent screen 
- [LIME-1368](https://govukverify.atlassian.net/browse/LIME-1368
)
[LIME-1368]: https://govukverify.atlassian.net/browse/LIME-1368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1368 Welsh translation added for consent screen

---

src/app/drivingLicence/controllers/root.js
src/app/drivingLicence/controllers/root.test.js

ECS logging added to root controller
To facilitate troubleshooting when malformed person info data is received from our DL API on auth source journey 
- [LIME-1369](https://govukverify.atlassian.net/browse/LIME-1369)
Expected sharedClaims JSON with all fields present:
`{
"@context": [
"https://www.w3.org/2018/credentials/v1",
"https://vocab.london.cloudapps.digital/contexts/identity-v1.jsonld"
],
"name": [
{
"nameParts": [
{
"type": "Given",
"value": "KENNETH"
},
{
"type": "FamilyName",
"value": "DECERQUEIRA"
}
]
}
],
"birthDate": [
{
"value": "1965-07-08"
}
],
"drivingPermit": [
{
"personalNumber": "DOE99751010AL9OD",
"expiryDate": "2022-02-02",
"issueDate": "2012-02-02",
"issueNumber": "13",
"issuedBy": "DVLA",
"fullAddress": "8 HADLEY ROAD BATH BA2 5AA"
}
]
}`
**Evidence for logging …

LIME-1369 logging added for auth source route

---

package.json
src/app/drivingLicence/controllers/root.js
test/browser/features/English/DVA/DVAAuthSource.feature
test/browser/features/English/DVLA/DVLAAuthSource.feature
test/browser/features/Welsh/DVA/WelshDVAAuthSource.feature
test/browser/features/Welsh/DVLA/WelshDVLA.feature
test/browser/features/Welsh/DVLA/WelshDVLAAuthSource.feature
test/browser/pages/CheckYourDetailsPage.js
test/browser/pages/consent.js
test/browser/pages/index.js
test/browser/step_definitions/CheckYourDetailsStepDefs.js
test/browser/step_definitions/consent.js
test/browser/step_definitions/details.js
test/browser/support/env.js
test/browser/support/setup.js
test/mocks/mappings/dl-check-error.json
test/mocks/mappings/driving-licence-dva-auth-source.json
test/mocks/mappings/driving-licence-dvla-auth-source.json
test/mocks/mappings/driving-licence-fail.json
test/mocks/mappings/drivingLicence-slow.json

Added new tests for DL Auth Source
Split between DVA Auth Source and DVLA Auth Source
Tests added for both DVA and DVLA Auth Source Welsh Translation Tests
- [LIME-1363](https://govukverify.atlassian.net/browse/LIME-1363)
All Tests passed locally when using 'yarn test:browser:ci:auth' command
[LIME-1363]: https://govukverify.atlassian.net/browse/LIME-1363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1363: Added new Auth Source UI Tests (including Welsh Translation)

---

src/views/drivingLicence/check-your-details.html
test/browser/pages/CheckYourDetailsPage.js

This is an accessibility requirement for the Authoritative Source initiative to make a single definition list for UK driving licences to aid the use of assistive tech.
The definition list for UK driving licences was implemented as 3 definition lists, this has been changed to be one list for either DVA or DVLA in the check-your-details.html view.
Changes show the correct form format in check your details view.
Check your details page for DVLA:
Check your details page for DVA:
- [LIME-1492](https://govukverify.atlassian.net/browse/LIME-1492)
[LIME-1492]: https://govukverify.atlassian.net/browse/LIME-1492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1492 Accessibility | Made a single definition list

---

package.json
src/views/drivingLicence/check-your-details.html
test/browser/pages/CheckYourDetailsPage.js
yarn.lock

Upgraded hmpo-components to version 6.4.0 (includes patch for radio button hints)
Removed temporary bug fix on check-details view (now displaying correctly in latest hmpo-components version)

LIME-1491 - HMPO-Components Uversion upgrade for radio button hint text

---

src/views/drivingLicence/check-your-details.html

Updated DVA Date formats to appear in European format rather than ISO

LIME-1493 - Updating DVA date formats

---

src/views/drivingLicence/check-your-details.html

Apply the govuk-input--extra-letter-spacing CSS class to improve readability of licence numbers. 
govuk-input--extra-letter-spacing class added to the value key in check-your-details.html
- [LIME-1494 ](https://govukverify.atlassian.net/browse/LIME-1494 )

LIME-1494 Accessibility | extra letter spacing added to licence number in Check Your Details view

---

src/assets/scss/application.scss

Ensure the Govuk-summary-list__key elements are in bold primary text ($govuk-text-colour) 
Added  $govuk-text-colour to application.scss file
Summary list key elements were appearing as secondary text colour
- [LIME-1495 ](https://govukverify.atlassian.net/browse/LIME-1495 )

LIME-1495 updating summary-list_key elements to be in bold

---

.github/dependabot.yml

Changes made to update dependabot open PR limit to 20 due to present limit of 5 being too few given some PRs can be blocked for some time. 
This FE repo has no dependencies that require grouping so no update made regarding grouping dependencies. 
- [LIME-1229](https://govukverify.atlassian.net/browse/LIME-1229)
[LIME-1229]: https://govukverify.atlassian.net/browse/LIME-1229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1229 increases Dependabot open PR limit

---

.secrets.baseline
deploy/template.yaml

This is protected by a specific WAF for CloudFront
Added tags to exclude the origin load balancer from FMS as it has it's own CloudFront specific WAF
Added tags
to exclude the origin load balancer from FMS as it has it's own CloudFront specific WAF
https://govukverify.atlassian.net/browse/IPS-1407

Update to  exclude the origin load balancer from the regional FMS policy

---

package.json

Upgrading FE Vital signs to log max EventLoopDelay (fix brought in by latest patch version)

LIME-1546 Upgrading FE Vital signs to log max EventLoopDelay

---

src/locales/cy/fields.yml
src/locales/cy/pages.yml
src/locales/en/fields.yml
src/locales/en/pages.yml
src/views/drivingLicence/licence-issuer.html
test/browser/pages/licence-issuer.js

Update the hint text in the Driving Licence CRI, to provide clarity to a user on whether they should select ‘DVA’ or ‘DVLA’ on the 'Was your UK photocard driving licence issued by DVLA or DVA?' screen.
- Header updated to Was your UK photocard driving licence issued by DVLA or DVA?
- Browser test for licence issuer page updated to reflect title change
- hint added to licence issuer to fields.yml
- hints added to radio buttons in fields.yml
- addition of 'photocard' to radio button lebel in fields.yml
- text removed from details text in pages.yml
- continue button moved to sit below "Why we need to know this" component
English has been added temporarily to Welsh translation pages to pass pre-merge checks.
Screen matches new design:
UI tests pass:
Welsh translation added:
- …

LIME-1482 Updated licence issuer page for Low Confidence journey

---

src/locales/cy/fields.yml
src/locales/cy/pages.yml

To address welsh translation mismatch between an old and new version
Welsh translation updated for "You must select an option to continue" in fields.yml
and "Why do we need to know this?" in pages.yml 
- [LIME-1483](https://govukverify.atlassian.net/browse/LIME-1483)
[LIME-1483]: https://govukverify.atlassian.net/browse/LIME-1483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1482]: https://govukverify.atlassian.net/browse/LIME-1482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1483 Welsh content update

---

test/browser/features/English/DLCommon/DLCommon.feature
test/browser/features/English/DLCommon/WelshDLCommon.feature
test/browser/features/Welsh/DVA/WelshDVA.feature
test/browser/features/Welsh/DVLA/WelshDVLA.feature
test/browser/pages/licence-issuer.js
test/browser/step_definitions/licence-issuer.js
yarn.lock

Added new featurefile for common tests
Added tests for landing page headers/ footers/ page content/ page elements
To reduce the associated need for Common tests on the BE DL Repo
- [LIME-1530](https://govukverify.atlassian.net/browse/LIME-1530)
All Tests passed locally in Dev: 
[LIME-1530]: https://govukverify.atlassian.net/browse/LIME-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1530 - Added new Common Tests for Driving Licence Landing Page

---

src/locales/en/default.yml

The aria-label for the language toggle when /check page is in English should also be in English so that English speaking screenreader users receive instructions in a language they understand.
Updated aria-label in english locale file
- [LIME-1510](https://govukverify.atlassian.net/browse/LIME-1510)
[LIME-1510]: https://govukverify.atlassian.net/browse/LIME-1510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1510 Language Toggle: Updated aria-label

---

src/locales/en/fields.yml
src/views/drivingLicence/licence-issuer.html
test/browser/features/English/DLCommon/DLCommon.feature

H1 heading for the "Was your UK photocard driving licence issued by DVLA or DVA?" page was not correctly grouped with the form in line with Design System Guidance.
H1 Inclusion: The H1 element was placed within the form group.
Legend Markup: The H1 is now marked up as the form legend using <legend> tags for improved semantic structure.
- [LIME-1558](https://govukverify.atlassian.net/browse/LIME-1558)
[LIME-1558]: https://govukverify.atlassian.net/browse/LIME-1558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1558 Include H1 in form group

---

eslint.config.mjs
package.json
test/browser/step_definitions/CheckYourDetailsStepDefs.js
test/browser/step_definitions/DrivingLicenceStepDefs.js
test/browser/step_definitions/consent.js
test/browser/step_definitions/errors.js
test/browser/step_definitions/licence-issuer.js
yarn.lock

This PR contains a new step in the tests. Upon each page loaded: Check your Details, Consent, Driving Licence Details and Licence Issuer Pages. The Axe Accessibility Script will execute against the 'wcg2aa' (WCGA 2.2 AA) ruleset. And report out any violations as warnings.
- [LIME-1514](https://govukverify.atlassian.net/browse/LIME-1514)
all tests pass locally following code changes:
[LIME-1514]: https://govukverify.atlassian.net/browse/LIME-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1514: Added Axe Accessibility Script to run on page load

---

.github/workflows/checks.yml

Bumped the GH Action to use the new SonarCloud GH Action
version pin
Upstream action deprecated
https://govukverify.atlassian.net/browse/IPS-1428

Updating SonarCube GH Action to avoid deprecation

---

src/locales/cy/default.yml
src/locales/en/default.yml
src/views/drivingLicence/licence-issuer.html
test/browser/features/English/DVA/DVA.feature
test/browser/features/English/DVA/DVAAuthSource.feature
test/browser/features/English/DVLA/DVLA.feature
test/browser/features/English/DVLA/DVLAAuthSource.feature
test/browser/features/Welsh/DVA/WelshDVA.feature
test/browser/features/Welsh/DVA/WelshDVAAuthSource.feature
test/browser/features/Welsh/DVLA/WelshDVLA.feature
test/browser/features/Welsh/DVLA/WelshDVLAAuthSource.feature
test/browser/pages/licence-issuer.js

serviceName amended to remove _"... - Prove your identity" from page tab titles in DL FE. FE tests also updated to reflect this and the removal adding of 'One Login' to the pageTitle suffix brought in by the Common Express update.
To keep this service in line with other services of the programme and fix failing tests as a result of the Common Express update beyond 10.1.x.
- [LIME-1508](https://govukverify.atlassian.net/browse/LIME-1508)
- [LIME-1591](https://govukverify.atlassian.net/browse/LIME-1591)
[LIME-1508]: https://govukverify.atlassian.net/browse/LIME-1508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1591]: https://govukverify.atlassian.net/browse/LIME-1591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …

LIME-1508 pageTitle and tests amended

---

.github/workflows/checks.yml
.husky/pre-commit
.husky/pre-push
package.json
test/browser/features/English/DLCommon/DLCommon.feature
test/browser/features/English/DVA/DVA.feature
test/browser/features/English/DVLA/DVLA.feature
test/browser/pages/DrivingLicencePage.js
test/browser/pages/licence-issuer.js
test/browser/step_definitions/DrivingLicenceStepDefs.js
test/browser/step_definitions/licence-issuer.js
yarn.lock

Added new AC Test to check for device Intelligence cookie and that it has a value
New AC Test Added to fraud.feature
To check that the new device intelligence cookie has been loaded correctly after Fraud Check Page load
- [LIME-1641](https://govukverify.atlassian.net/browse/LIME-1641)
[LIME-1641]: https://govukverify.atlassian.net/browse/LIME-1641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1641 Add Device Intelligence AC Tests to check for Cookie

---

package.json
test/browser/features/English/DLCommon/DLCommon.feature
test/browser/features/English/DVA/DVA.feature
test/browser/features/English/DVA/DVAAuthSource.feature
test/browser/features/English/DVLA/DVLA.feature
test/browser/features/English/DVLA/DVLAAuthSource.feature
test/browser/step_definitions/CheckYourDetailsStepDefs.js
test/browser/step_definitions/DrivingLicenceStepDefs.js
test/browser/step_definitions/consent.js
test/browser/step_definitions/errors.js
test/browser/step_definitions/licence-issuer.js
yarn.lock

Updated Axe Accessibility Tests:
Removed the Axe Scan from the background step of the Scenarios and within Error Page Step Added Specific Test for Passport Details Page and Passport Error Page which runs the Axe Scan
This will allow for clearer reporting and troubleshooting of any accessibility issues going forward
- [LIME-1637](https://govukverify.atlassian.net/browse/LIME-1637)
Test Evidence: 
[LIME-1637]: https://govukverify.atlassian.net/browse/LIME-1637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1637 - DL FE - Split out Axe Scan into Specific Tests for better visibility

---

deploy/template.yaml

Replace DLOnlyOneTaskCountAlarm with DLBelowMinTaskCountAlarm
So that the alarm is based on the min taskcount of each environment
- [LIME-1665](https://govukverify.atlassian.net/browse/LIME-1665)
[LIME-1665]: https://govukverify.atlassian.net/browse/LIME-1665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1665 Replace DLOnlyOneTaskCountAlarm with DLBelowMinTaskCountAlarm so that the alarm is based on the min taskcount of each environment

---

.github/workflows/post-merge-to-build.yml
.github/workflows/post-merge-to-dev.yml

GHA to use the latest version of the Cosign package as all older versions are now unsupported. Requires update of [devplatform-upload-action-ecr](https://github.com/govuk-one-login/devplatform-upload-action-ecr) package.
- [LIME-1755](https://govukverify.atlassian.net/browse/LIME-1755)
[LIME-1755]: https://govukverify.atlassian.net/browse/LIME-1755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1755 bump upload-action-ecr versions

---

deploy/template.yaml

Enable may2025RebrandEnabled in integration
To align with the overall implementation plan and as confirmed that integration enablement supports E2E testing beginning W/C 14th July.
- [LIME-1749](https://govukverify.atlassian.net/browse/LIME-1749)
[LIME-1749]: https://govukverify.atlassian.net/browse/LIME-1749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1749 Enable branding in int

---

yarn.lock

Re-installed dependencies to update the package-lock.json to bring in v1.3.12 of @govuk-one-login/frontend-ui
To pull in changes that fix a url parameters issue present in v1.3.6
- [LIME-1786](https://govukverify.atlassian.net/browse/LIME-1786)
[LIME-1786]: https://govukverify.atlassian.net/browse/LIME-1786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1786 Upgrade to frontend-ui v1.3.12

---

src/app/drivingLicence/fields.js
src/locales/cy/fields.yml

Fixing the Validation on DVA Welsh Licence Number to return "Rhowch y rhif yn union fel mae'n ymddangos ar eich trwydded yrru" when entering a licence number with an alphanumeric combination (e.g. 123456AA)
- [LIME-666](https://govukverify.atlassian.net/browse/LIME-666)
[LIME-666]: https://govukverify.atlassian.net/browse/LIME-666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-666: Fixing Incorrect Validation on DVA Welsh Licence Number.

---

deploy/template.yaml

Enable may2025RebrandEnabled in Production.
To align with the Go Live for Branding Refresh on the 31st July.

LIME-1722: Enable Rebranding in Production.

---

test/browser/features/English/DVA/DVA.feature
test/browser/features/English/DVA/DVAAuthSource.feature
test/browser/features/English/DVLA/DVLA.feature
test/browser/features/English/DVLA/DVLAAuthSource.feature
test/browser/features/Welsh/DVA/WelshDVA.feature
test/browser/features/Welsh/DVA/WelshDVAAuthSource.feature
test/browser/features/Welsh/DVLA/WelshDVLA.feature
test/browser/features/Welsh/DVLA/WelshDVLAAuthSource.feature
test/browser/pages/CheckYourDetailsPage.js
test/browser/pages/DVADetailsEntryPage.js
test/browser/pages/DrivingLicencePage.js
test/browser/pages/UniversalSteps.js
test/browser/step_definitions/CheckYourDetailsStepDefs.js
test/browser/step_definitions/DrivingLicenceStepDefs.js
test/browser/step_definitions/UniversalStepDefs.js

Tests added for all journeys (DVA/ DVLA, DVA Auth Source/ DVLA Auth Source) English and Welsh Test checks for back button, confirms text is correct, clicks the back button, and validates it is back on the correct page
- [LIME-1831](https://govukverify.atlassian.net/browse/LIME-1831)
All Tests passed locally:
[LIME-1831]: https://govukverify.atlassian.net/browse/LIME-1831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1831 - Update AC tests with coverage for 'Back' Button
